# Backend Dockerfile
FROM python:3.11-slim

WORKDIR /src

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Copy application code
COPY . .




# Run the application
CMD ["python", "worker.py"]